#------------------------------------------------------------------------------
# General
#------------------------------------------------------------------------------
name: "Neonnsoft devlog"
description: "Stay up to date with what's going on at Neonnsoft."
language: "en"

url: "blog.neonnsoft.com"
baseurl: ""

#------------------------------------------------------------------------------
# Markdown processor and code highlighting
#------------------------------------------------------------------------------
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

#------------------------------------------------------------------------------
# Pagination and friendly URLs
#------------------------------------------------------------------------------
paginate: 3
paginate_path: /page-:num
permalink: /:title

#------------------------------------------------------------------------------
# Social sharing, comments and RSS.
#------------------------------------------------------------------------------
disqus-id: yourusername

enable-share: true
twitter: yourusername
github: iamsegfault
google: +yourusername

rss-feed-limit: 10
rss-show-full: false

#------------------------------------------------------------------------------
# Configuration, plugins, gems, etc..
#------------------------------------------------------------------------------
source: .
destination: ./_site
gems: ['jekyll-paginate', 'github-pages']

sass:
    style: :compressed
    sass_dir: assets/css/
